okta:
  OKTA_AUTH_URL: "Okta auth URL"
  OKTA_CLIENT_ID: "Okta client ID"
  OKTA_ENDPOINTS: [ 'admin' ]
summarization_model:
  API_BASE: "LLM api server"
  API_KEY: "API key"
  MAX_COMPLETION: 700
  BATCH_SIZE: 4
  MODELS_JSON: "src/config/models.json"
qa_model:
  API_BASE: "QA model API server"
  API_KEY: "api key"
  MODEL: "mistralai/mixtral-8x7b-instruct-v0.1"
  MAX_TOKEN: 1024
  MAX_COMPLETION: 700
  SIMIL_TOP_K: 10 # Retrieve TOP_K most similar docs from the PGVector store
  CHUNK_SIZE: 512
  CHUNK_OVERLAP: 20
  NUM_QUERIES: 3
embedder:
  API_BASE: "Embedding model API server"
  API_KEY: "api key"
  MODEL: "nvidia/nv-embedqa-e5-v5"
  VECTOR_DIM: 1024
  BATCH_SIZE: 1
reranker:
  RERANK_ENABLED: True
  API_BASE: "Re-ranking model api server"
  API_KEY: "api key"
  MODEL: "nvidia/nv-rerankqa-mistral-4b-v3"
  RERANK_TOP_N: 5 # Rerank and pick the 5 most similar docs
database:
  PG_HOST: "Database host" #"localhost"
  PG_PORT: 5432
  PG_USER: DB_USER
  PG_PASSWD: DB_PASSWORD
  PG_DATABASE: "vectordb"
  PG_TABLE: "embeddings"
server:
  HOST: "0.0.0.0"
  PORT: 5000
  NUM_WORKERS: 4
  PDF_READER: pypdf # default PDF parser
  FILE_PATH: "/mnt/data"
  RELOAD: False
  AUTH: basic
  JWT_SECRET_KEY: "secret key for JWT"
stt:
  STT_API: "http://localhost:9000/api/v1" # STT-server URL
  AUTH_KEY: "your STT api auth key"
email:
  SMTP_SERVER: "email server"
  SENDER: "send email"
  SUMMARIZER_URL: "Summarizer Client URL" # "http://localhost:4200"
  


